// Code generated by "stringer -type=TaskStat btask.go"; DO NOT EDIT.

package btask

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StUnknown-0]
	_ = x[StRunnable-1]
	_ = x[StPerfGranted-2]
	_ = x[StResume-3]
	_ = x[StRunResult-4]
}

const _TaskStat_name = "StUnknownStRunnableStPerfGrantedStResumeStRunResult"

var _TaskStat_index = [...]uint8{0, 9, 19, 32, 40, 51}

func (i TaskStat) String() string {
	if i < 0 || i >= TaskStat(len(_TaskStat_index)-1) {
		return "TaskStat(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TaskStat_name[_TaskStat_index[i]:_TaskStat_index[i+1]]
}
